apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "charts.fullname" . }}-config
  labels:
  {{- include "charts.labels" . | nindent 4 }}
data:
  {{- range $k, $v := .Values.configuration }}
  {{ $k }}: {{ $v | quote }}
  {{- end }}
  IDENTITYFILE: "/ssh/id_rsa"
  KNOWN_HOSTS: "/ssh/known_hosts"
